// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4km-aHvRYdofBFLCLYWXlarY-Jsj_CBk',
    appId: '1:400489519426:web:2c8cb3923587e68acb10db',
    messagingSenderId: '400489519426',
    projectId: 'clearo-73407',
    authDomain: 'clearo-73407.firebaseapp.com',
    storageBucket: 'clearo-73407.firebasestorage.app',
    measurementId: 'G-STB6L3H062',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB10Un-rz2kLakGCXwBpYdfCKB4I8WCxS8',
    appId: '1:400489519426:android:a5d1d8692c2b0366cb10db',
    messagingSenderId: '400489519426',
    projectId: 'clearo-73407',
    storageBucket: 'clearo-73407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3jKJ8m3v-PVYuBnfJJ2P7wgT_E--TyyE',
    appId: '1:400489519426:ios:148a4e0be17d3fb4cb10db',
    messagingSenderId: '400489519426',
    projectId: 'clearo-73407',
    storageBucket: 'clearo-73407.firebasestorage.app',
    iosBundleId: 'com.example.clearo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4km-aHvRYdofBFLCLYWXlarY-Jsj_CBk',
    appId: '1:400489519426:web:33a053020bb7b4cbcb10db',
    messagingSenderId: '400489519426',
    projectId: 'clearo-73407',
    authDomain: 'clearo-73407.firebaseapp.com',
    storageBucket: 'clearo-73407.firebasestorage.app',
    measurementId: 'G-XQSKJ9J9FF',
  );
}
